#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = ' {{ if .SSHSession }} {{ end }}{{ .UserName }} '
    background = 'p:yellow'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ path .Path .Location }} '
    background = 'p:orange'
    foreground = 'p:white'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:black{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:white{{ end }}',
      '{{ if gt .Ahead 0 }}p:white{{ end }}'
    ]
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}',
      '{{ if gt .Ahead 0 }}#49416D{{ end }}',
      '{{ if gt .Behind 0 }}#7A306C{{ end }}'
    ]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'
    background = 'p:green'
    foreground = 'p:black'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      branch_icon = ''
      branch_max_length = 50
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    template = '  '
    background = 'p:yellow'
    foreground = 'p:white'
    Text = ''
    Duration = 0
    NameLength = 0

  [[blocks.segments]]
    type = 'status'
    style = 'diamond'
    background_templates = ['{{ if gt .Code 0 }}p:red{{ end }}']
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''
    template = ' {{ if gt .Code 0 }}{{ else }}{{ end }} '
    background = 'p:blue'
    foreground = 'p:white'
    Text = ''
    Duration = 0
    NameLength = 0

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000
      style = 'austin'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'p:blue'
    background = 'transparent'
    template = '〉'

[transient_prompt]
  foreground = 'p:blue'
  background = 'transparent'
  template = '〉 '

[secondary_prompt]
  foreground = 'p:blue'
  background = 'transparent'
  template = '〉〉 '

[palette]
  black = '#262B44'
  blue = '#4B95E9'
  green = '#59C9A5'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#E0DEF4'
  yellow = '#F3AE35'
