;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        counsel-M-x
        doom/backward-to-bol-or-indent
        ivy-alt-done
        org-beginning-of-line
        org-open-line
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        +fabio/mark-symbol-or-mark-next-like-this
        ))
