;;; ~/.dotfiles/doom.d/custom.el -*- lexical-binding: t; -*-

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(objed-cmd-alist
   '((left-char . char)
     (right-char . char)
     (forward-word . word)
     (capitalize-word . word)
     (backward-word . word)
     (move-beginning-of-line . line)
     (move-end-of-line . line)
     (previous-line . line)
     (next-line . line)
     (beginning-of-buffer . buffer)
     (end-of-buffer . buffer)
     (scroll-up-command . char)
     (scroll-down-command . char)
     (View-scroll-half-page-forward . char)
     (View-scroll-half-page-backward . char)
     (move-to-window-line-top-bottom . line)
     (imenu . line)
     (backward-paragraph . paragraph)
     (forward-paragraph . paragraph)
     (fill-paragraph . textblock)
     (down-list . sexp)
     (backward-up-list . sexp)
     (up-list . sexp)
     (forward-sexp . sexp)
     (backward-sexp . sexp)
     (indent-pp-sexp . bracket)
     (back-to-indentation . line)
     (org-beginning-of-line . line)
     (org-end-of-line . line)
     (recenter-top-bottom . line)
     (forward-sentence . sentence)
     (org-forward-sentence . sentence)
     (backward-sentence . sentence)
     (org-backward-sentence . sentence)
     (org-backward-element . block)
     (beginning-of-defun . defun)
     (end-of-defun . defun)
     (outline-previous-visible-heading . section)
     (outline-next-visible-heading . section)
     (org-previous-visible-heading . section)
     (comint-previous-prompt . output)
     (comint-next-prompt . output)
     (forward-button . face)
     (backward-button . face)
     (sgml-skip-tag-backward . tag)
     (Info-next-reference . face)
     (Info-prev-reference . face)
     (objed-next-identifier . identifier)
     (objed-prev-identifier . identifier)
     (objed-first-identifier . identifier)
     (objed-last-identifier . identifier)
     (yank . region)
     (yank-pop . region)
     (kill-buffer . char)
     (kill-this-buffer . char)
     (doom/backward-to-bol-or-indent . line)
     (doom/forward-to-last-non-comment-or-eol . line))))
